import { SidebarProvider, SidebarTrigger } from '~/components/ui/sidebar'
import Providers from '../providers'
import { AppSidebar } from '../components/AppSidebar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
  return (
    <main>
      <Providers>
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger />
          <section className="w-full">{children}</section>
        </SidebarProvider>
      </Providers>
    </main>
  )
}
