import Providers from '../providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function DashboardLayout({ children }) {
  return (
    <main>
      <Providers>{children}</Providers>
    </main>
  )
}
